server:
  port: 8003
spring:
  application:
    name: provider-comment
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      profile: prod
      #失败快速相应
      fail-fast: true
      label: master
      name: ${spring.application.name},application-rabbitmq

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:password123@localhost:8010/eureka/