server:
  port: 8011
spring:
  application:
    name: discovery-zuul
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      profile: dev
      #失败快速相应
      fail-fast: true
      label: master
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true