server:
  port: 8003
spring:
  application:
    name: provider-release
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      profile: dev
      #失败快速相应
      fail-fast: true
      label: master
      name: ${spring.application.name},discovery-rabbitmq